document.write('<DIV id=bg></DIV>');
document.write('<DIV class=hidden id=selectItem >');
document.write('<DIV class=\"tit1 bgc_ccc move\" onmousedown=drag(event,this)>');
document.write('<H2 style=\"margin-right:270px; padding-left:8px;height:29px; line-height:29px; vertical-align:middle;color:#fff;\" class=left>请选择城市</H2><SPAN class=\"pointer\" style=\"height:29px; color:#fff;line-height:29px; vertical-align:middle;\" onclick=openBg(0);openSelect(0);>[关闭]</SPAN> </DIV>');
document.write('<DIV class=\"cont\">');
document.write('<p>华北-东北： <a href=\"http://www.eduease.com/\">北京</a> <a href=\"http://sjz.eduease.com/\">石家庄</a> <a href=\"http://tj.eduease.com/\">天津</a> <a href=\"http://dl.eduease.com/\">大连</a> <a href=\"http://sy.eduease.com/\">沈阳</a> <a href=\"http://cc.eduease.com/\">长春</a> <a href=\"http://heb.eduease.com/\">哈尔滨</a> <a href=\"http://hhht.eduease.com/\">呼和浩特</a></p>');
document.write('<p class=\"bgc_f5f5f5 \">华东地区 ： <a href=\"http://sh.eduease.com/\">上海</a> <a href=\"http://nj.eduease.com/\">南京</a> <a href=\"http://su.eduease.com/\">苏州</a> <a href=\"http://hz.eduease.com/\">杭州</a>  <a href=\"http://hf.eduease.com/\">合肥</a> <a href=\"http://fz.eduease.com/\">福州</a> <a href=\"http://jn.eduease.com/\">济南</a> <a href=\"http://qd.eduease.com/\">青岛</a></p>');
document.write('<p>华南-华中： <a href=\"http://gz.eduease.com/\">广州</a> <a href=\"http://sz.eduease.com/\">深圳</a> <a href=\"http://wh.eduease.com/\">武汉</a> <a href=\"http://cs.eduease.com/\">长沙</a> <a href=\"http://zz.eduease.com/\">郑州</a> <a href=\"http://nc.eduease.com/\">南昌</a></p>');
document.write('<p class=\"bgc_f5f5f5 \">西北-西南： <a href=\"http://wlmq.eduease.com/\">乌鲁木齐</a> <a href=\"http://ty.eduease.com/\">太原</a> <a href=\"http://lz.eduease.com/\">兰州</a> <a href=\"http://xa.eduease.com/\">西安</a> <a href=\"http://cd.eduease.com/\">成都</a> <a href=\"http://cq.eduease.com/\">重庆</a> <a href=\"http://km.eduease.com/\">昆明</a> <a href=\"http://gy.eduease.com/\">贵阳</a> <a href=\"http://nn.eduease.com/\">南宁</a></p>');
document.write('</DIV>');
document.write('<DIV class=cont>');
document.write('<DIV id=selectSub></DIV>');
document.write('</DIV>');
document.write('</DIV>');
